spring:
  application:
    name: "configserver"
  profiles:
    active: git
    # active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/ankushgoyal27/easybytes-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

        # native:
          # search-locations: "classpath:/config"
          # search-locations: "file:///Users//ag//Desktop//Ankush//config"
    rabbitmq:
      host: "localhost"
      port: 5672
      username: "guest"
      password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "3F3BC1AB91FD472C51BA56BB3F359"
server:
  port: 8071



